Replace stdlib/**/*.scala with stdlib/*-semanticdb.jar
This patch allows us to move forward with the symbol table, however
it also introduces several breakages:

1) rscNative no longer links, because some of the JDK functionality
that we're using is not supported in Scala Native:

> rscNative/nativeLink
[info] Linking (2316 ms)
[error] cannot link: @java.net.URL::hashCode_i32
[error] cannot link: @java.net.URL::openStream_java.io.InputStream
[error] unable to link
[error] (rscNative/compile:nativeLinkNIR) unable to link

2) rsc.typecheck.Re2sTests.typecheck no longer workds, because
the old Rsc symbol format is incompatible with the SemanticDB v3
symbol format that is used in the new stdlib.

/Users/eburmako/Projects/rsc/examples/re2s/src/main/scala/java/util/regex/CharClass.scala:23: error: unbound: value _root_.scala.Array#.length
  private var len: Int = r.length
                           ^
/Users/eburmako/Projects/rsc/examples/re2s/src/main/scala/java/util/regex/CharClass.scala:28: error: unbound: value _root_.scala.Array#.length
    if (r.length < newLen) {
          ^
...
X rsc.typecheck.Re2sTests.typecheck re2s 911ms
  utest.AssertionError: assert(false)
    utest.asserts.Asserts$.assertImpl(Asserts.scala:114)
    rsc.tests.RscTests$class.assertRun(RscTests.scala:23)
    rsc.typecheck.Re2sTests$.assertRun(Re2sTests.scala:8)
    rsc.typecheck.Re2sTests$$anonfun$1$$anonfun$apply$1.apply(Re2sTests.scala:12)
    rsc.typecheck.Re2sTests$$anonfun$1$$anonfun$apply$1.apply(Re2sTests.scala:9)